//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Domain.Api.Ressources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Arquivos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Arquivos() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Domain.Api.Ressources.Arquivos", typeof(Arquivos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;pt-BR&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Serviços WSDL&lt;/title&gt;
        ///
        ///    &lt;!-- Bootstrap 4 --&gt;
        ///    &lt;link rel=&quot;stylesheet&quot;
        ///          href=&quot;https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css&quot;&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body class=&quot;bg-light&quot;&gt;
        ///
        ///    &lt;div class=&quot;container mt-5&quot;&gt;
        ///        &lt;div class=&quot;row justify-content-center&quot;&gt;
        ///            &lt;div class=&quot;col-md-8&quot;&gt;
        ///
        ///                &lt;div class=&quot;card shadow-sm&quot;&gt;
        ///                    &lt;div class=&quot;card-header bg-pri [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Lista_servicos {
            get {
                return ResourceManager.GetString("Lista_servicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///&lt;/-----# ID @ID
        ///#----- DATA:
        ///@DATA
        ///#----- :DATA
        ///#----- SERVICO:
        ///@SERVICO
        ///#----- :SERVICO
        ///#----- CONTEUDO:
        ///@CONTEUDO
        ///#----- :CONTEUDO 
        ///#-----/&gt;
        ///.
        /// </summary>
        internal static string TEMPLETE_DATA_LOG {
            get {
                return ResourceManager.GetString("TEMPLETE_DATA_LOG", resourceCulture);
            }
        }
    }
}
